CREATE TABLE [dbo].[ExecRequestsHistory] (

	[Edition] varchar(128) NULL, 
	[WorkSpaceId] varchar(128) NULL, 
	[ArtifactId] varchar(128) NULL, 
	[Query_Time_sec] int NULL, 
	[distributed_statement_id] uniqueidentifier NULL, 
	[database_name] varchar(200) NULL, 
	[submit_time] datetime2(6) NULL, 
	[start_time] datetime2(6) NULL, 
	[end_time] datetime2(6) NULL, 
	[is_distributed] int NOT NULL, 
	[is_accelerated] int NOT NULL, 
	[statement_type] varchar(128) NULL, 
	[total_elapsed_time_ms] bigint NULL, 
	[login_name] varchar(200) NULL, 
	[row_count] bigint NULL, 
	[status] varchar(200) NULL, 
	[session_id] int NULL, 
	[connection_id] uniqueidentifier NULL, 
	[program_name] varchar(128) NULL, 
	[batch_id] uniqueidentifier NULL, 
	[root_batch_id] uniqueidentifier NULL, 
	[query_hash] varchar(200) NULL, 
	[label] varchar(8000) NULL, 
	[result_cache_hit] int NULL, 
	[sql_pool_name] varchar(128) NULL, 
	[error_code] int NULL, 
	[error_severity] int NULL, 
	[error_state] int NULL, 
	[allocated_cpu_time_ms] bigint NULL, 
	[data_scanned_remote_storage_mb] decimal(18,3) NULL, 
	[data_scanned_memory_mb] decimal(18,3) NULL, 
	[data_scanned_disk_mb] decimal(18,3) NULL, 
	[is_using_external_api] int NULL, 
	[command] varchar(max) NULL
);